on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y python3.8 python3.8-venv python3-pip openjdk-17-jdk unzip zip wget \
            libtinfo5 libncurses6 libffi-dev libssl-dev git make autoconf automake libtool pkg-config

      - name: Install Buildozer
        run: |
          python3.8 -m pip install --upgrade pip
          python3.8 -m pip install --user --upgrade buildozer cython virtualenv

      - name: Build APK
        run: |
          export PATH=$HOME/.local/bin:$PATH
          buildozer -v android debug

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: ./bin/*.apk
